Controllers/ContrateController.cs
using Microsoft.AspNetCore.Mvc;
using RoleTopMVC.Controllers;

namespace RoleTopem.Controllers
{
    public class ContrateController: AbstractController
    {
                public IActionResult Index()
        {
            
            return View();
            
        }
    
    }
}

Views/Shared/Erro.cshtml
@model RoleTopem.ViewModels.RespostaViewModel
<main>
    <h2>
        @Model.NomeView Que Pena, seu cadastro Não foi Concluido!
    </h2>
    <p>
        @Model.Mensagem
        <a asp-controller= "Home" asp-action="Index">Voltar para a Home</a> 
    </p>
</main>

Views/Shared/Sucesso.cshtml
@model RoleTopem.ViewModels.RespostaViewModel
<main>
    <h2>
        @Model.NomeView Parabens, seu cadastro foi feito com sucesso!
    </h2>
    <p>
        @Model.Mensagem
        <a asp-controller= "Home" asp-action="Index">Voltar para a Home</a> 
    </p>
</main>

Views/Shared/_HeaderHomePage.cshtml
<div id="cabeçalho">
            <a href="index.html"><img id="logo" src="img/logo.png" /></a>
            <div id="redes-sociais">
                <img src="img/insta.png" />
                <img src="img/facebook.png" />
                <img src="img/youtube.png" />
            </div>

Views/Shared/_Layout.cshtml
@model RoleTopMVC.ViewModels.BaseViewModel
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <!-- PASSOS DO MENU RESPONSIVO -->
    <!-- PASSO 1 - Certifique-se de que essa linha abaixo existe no seu código -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RoleTop</title>
   
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Londrina+Solid:900%7COpen+Sans" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    @if(!"Home".Equals(@Model.NomeView))
    {
        <link href="~/css/style-secondary-pages.css" rel="stylesheet" type="text/css">
        <link href="~/css/style-form-pages.css" rel="stylesheet" type="text/css">
    }
    @if("Galeria".Equals(@Model.NomeView))
    {
        <link href="~/css/style-secondary-pages.css" rel="stylesheet" type="text/css">
        <link href="~/css/style-form-pages.css" rel="stylesheet" type="text/css">
        <link href="~/css/style-galeria.css" rel="stylesheet" type="text/css">
    }
    <!-- PASSO 2 - Copie a linha do <script> abaixo para o seu HTML -->
    <!-- Importar o Font Awesome para o projeto -->
    <script src="https://kit.fontawesome.com/349a64cb04.js"></script>
</head>
<body class="flex-container">
    <header>
        <nav>
            <div class="section-container">
                <ul>
                    <!-- PASSO 3 - Adicione esse li à sua ul -->
                    <li id="bt-mobile-menu">
                        <!-- HTML para colocar os ícones do FA -->
                        <a href="javascript:void(0);" class="icon" onclick="toggleMobileMenu()">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                    <!-- PASSO 4 - Adicione essa class="bt-common-menu" nas suas li -->
                    <!-- PASSO 5 - Adicione o onclick="toggleMobileMenu()" nas tags a -->
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Home" asp-action="Index" class="active">Home</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Galeria" asp-action="Index">Galeria</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Contrate" asp-action="Index">Contrate</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Historia" asp-action="Index">História</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()"  asp-controller="Contato" asp-action="Index">Contato</a></li>
                    @if(string.IsNullOrEmpty(@Model.UsuarioEmail))
                    {
                        <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Cadastro" asp-action="Index">Login/Cadastro</a></li>
                    }
                    else
                    {
                        <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Cliente" asp-action="Logoff">Logoff</a></li>
                        <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Cliente" asp-action="Historico">Pedidos</a></li>
                    }

                </ul>
            </div>
        </nav>
    </header>

    @RenderBody()
        
    </div>

    <footer>
        <address>
            Avenida de Limeira, 539 - Campos Elíseos - SP
            <br />
            roletop@roletop.com
            <br />
            11 1234 6789
        </address>
        <a href="index.html">Home</a>
        <a href ="historia.html">Historia</a>
        <a href="contrate.html"> Reservar</a>
        <a href="galeria.html"> Galeria de Fotos</a>
        <a href="contato.html"> Contato</a>

    </footer>
    <a href="#"><i class="material-icons comeback">
            expand_less
        </i></a>
</body>

</html>